[package]
name = "blue-recorder"
version = "0.1.4"
authors = ["Salem Yaslem <s@sy.sa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.13.2"
glib = "0.10.3"
rust-ini = "0.16"
regex = "1.4.3"
chrono = "0.4.19"
libappindicator = "0.5.2"
gettext-rs = "0.7.0"
subprocess = "0.2.6"
zbus = "1.8.0"
zvariant = "2.5.0"
gdk-pixbuf = "0.9.0"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
