[package]
name = "blue-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
gdk = { git = "https://github.com/gtk-rs/gtk4-rs.git", package = "gdk4"}
gdk-pixbuf = "0.9.0"
gettext-rs = "0.7.0"
gtk = { version = "0.4.8", package = "gtk4" }
gtk-sys = "0.15"
glib = "0.10.3"
libappindicator = "0.5.2"
rust-ini = "0.16"
regex = "1.4.3"
subprocess = "0.2.6"
zbus = "1.9.2"
zvariant = "2.10.0"

[dependencies.gio]
version = "0.15.0"
